// Türkiye 81 il + ilçe canonical dataset
// Kaynak: TÜİK resmi idari bölünme listesi
// slug: TR karakterler → ASCII dönüşümü (ç→c, ş→s, ğ→g, ü→u, ö→o, ı→i)

export function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/ç/g, 'c').replace(/ş/g, 's').replace(/ğ/g, 'g')
    .replace(/ü/g, 'u').replace(/ö/g, 'o').replace(/ı/g, 'i')
    .replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
}

export const TURKEY_CITIES: { name: string; plateCode: number; districts: string[] }[] = [
  { name: 'Adana', plateCode: 1, districts: ['Aladağ','Ceyhan','Çukurova','Feke','İmamoğlu','Karaisalı','Karataş','Kozan','Pozantı','Saimbeyli','Sarıçam','Seyhan','Tufanbeyli','Yumurtalık','Yüreğir'] },
  { name: 'Adıyaman', plateCode: 2, districts: ['Adıyaman Merkez','Besni','Çelikhan','Gerger','Gölbaşı','Kahta','Samsat','Sincik','Tut'] },
  { name: 'Afyonkarahisar', plateCode: 3, districts: ['Afyonkarahisar Merkez','Başmakçı','Bayat','Bolvadin','Çay','Çobanlar','Dazkırı','Dinar','Emirdağ','Evciler','Hocalar','İhsaniye','İscehisar','Kızılören','Sandıklı','Sinanpaşa','Sultandağı','Şuhut'] },
  { name: 'Ağrı', plateCode: 4, districts: ['Ağrı Merkez','Diyadin','Doğubayazıt','Eleşkirt','Hamur','Patnos','Taşlıçay','Tutak'] },
  { name: 'Amasya', plateCode: 5, districts: ['Amasya Merkez','Göynücek','Gümüşhacıköy','Hamamözü','Merzifon','Suluova','Taşova'] },
  { name: 'Ankara', plateCode: 6, districts: ['Akyurt','Altındağ','Ayaş','Bala','Beypazarı','Çamlıdere','Çankaya','Çubuk','Elmadağ','Etimesgut','Evren','Gölbaşı','Güdül','Haymana','Kahramankazan','Kalecik','Keçiören','Kızılcahamam','Mamak','Nallıhan','Polatlı','Pursaklar','Sincan','Şereflikoçhisar','Yenimahalle'] },
  { name: 'Antalya', plateCode: 7, districts: ['Akseki','Aksu','Alanya','Demre','Döşemealtı','Elmalı','Finike','Gazipaşa','Gündoğmuş','İbradı','Kaş','Kemer','Kepez','Konyaaltı','Korkuteli','Kumluca','Manavgat','Muratpaşa','Serik'] },
  { name: 'Artvin', plateCode: 8, districts: ['Ardanuç','Arhavi','Artvin Merkez','Borçka','Hopa','Kemalpaşa','Murgul','Şavşat','Yusufeli'] },
  { name: 'Aydın', plateCode: 9, districts: ['Bozdoğan','Buharkent','Çine','Didim','Efeler','Germencik','İncirliova','Karacasu','Karpuzlu','Koçarlı','Köşk','Kuşadası','Kuyucak','Nazilli','Söke','Sultanhisar','Yenipazar'] },
  { name: 'Balıkesir', plateCode: 10, districts: ['Altıeylül','Ayvalık','Balya','Bandırma','Bigadiç','Burhaniye','Dursunbey','Edremit','Erdek','Gömeç','Gönen','Havran','İvrindi','Karesi','Kepsut','Manyas','Marmara','Savaştepe','Sındırgı','Susurluk'] },
  { name: 'Bilecik', plateCode: 11, districts: ['Bilecik Merkez','Bozüyük','Gölpazarı','İnhisar','Osmaneli','Pazaryeri','Söğüt','Yenipazar'] },
  { name: 'Bingöl', plateCode: 12, districts: ['Adaklı','Bingöl Merkez','Genç','Karlıova','Kiğı','Solhan','Yayladere','Yedisu'] },
  { name: 'Bitlis', plateCode: 13, districts: ['Adilcevaz','Ahlat','Bitlis Merkez','Güroymak','Hizan','Mutki','Tatvan'] },
  { name: 'Bolu', plateCode: 14, districts: ['Bolu Merkez','Dörtdivan','Gerede','Göynük','Kıbrıscık','Mengen','Mudurnu','Seben','Yeniçağa'] },
  { name: 'Burdur', plateCode: 15, districts: ['Ağlasun','Altınyayla','Bucak','Burdur Merkez','Çavdır','Çeltikçi','Gölhisar','Karamanlı','Kemer','Tefenni','Yeşilova'] },
  { name: 'Bursa', plateCode: 16, districts: ['Büyükorhan','Gemlik','Gürsu','Harmancık','İnegöl','İznik','Karacabey','Keles','Kestel','Mudanya','Mustafakemalpaşa','Nilüfer','Orhaneli','Orhangazi','Osmangazi','Yıldırım','Yenişehir'] },
  { name: 'Çanakkale', plateCode: 17, districts: ['Ayvacık','Bayramiç','Biga','Bozcaada','Çan','Çanakkale Merkez','Eceabat','Ezine','Gelibolu','Gökçeada','Lapseki','Yenice'] },
  { name: 'Çankırı', plateCode: 18, districts: ['Atkaracalar','Bayramören','Çankırı Merkez','Çerkeş','Eldivan','Ilgaz','Kızılırmak','Korgun','Kurşunlu','Orta','Şabanözü','Yapraklı'] },
  { name: 'Çorum', plateCode: 19, districts: ['Alaca','Bayat','Boğazkale','Dodurga','İskilip','Kargı','Laçin','Mecitözü','Oğuzlar','Ortaköy','Osmancık','Sungurlu','Uğurludağ','Çorum Merkez'] },
  { name: 'Denizli', plateCode: 20, districts: ['Acıpayam','Babadağ','Baklan','Bekilli','Beyağaç','Bozkurt','Buldan','Çal','Çameli','Çardak','Çivril','Güney','Honaz','Kale','Merkezefendi','Pamukkale','Sarayköy','Serinhisar','Tavas'] },
  { name: 'Diyarbakır', plateCode: 21, districts: ['Bağlar','Bismil','Çermik','Çınar','Çüngüş','Dicle','Eğil','Ergani','Hani','Hazro','Kayapınar','Kocaköy','Kulp','Lice','Silvan','Sur','Yenişehir'] },
  { name: 'Edirne', plateCode: 22, districts: ['Edirne Merkez','Enez','Havsa','İpsala','Keşan','Lalapaşa','Meriç','Süloğlu','Uzunköprü'] },
  { name: 'Elazığ', plateCode: 23, districts: ['Ağın','Alacakaya','Arıcak','Baskil','Elazığ Merkez','Karakoçan','Keban','Kovancılar','Maden','Palu','Sivrice'] },
  { name: 'Erzincan', plateCode: 24, districts: ['Çayırlı','Erzincan Merkez','İliç','Kemah','Kemaliye','Otlukbeli','Refahiye','Tercan','Üzümlü'] },
  { name: 'Erzurum', plateCode: 25, districts: ['Aşkale','Aziziye','Çat','Hınıs','Horasan','İspir','Karaçoban','Karayazı','Köprüköy','Narman','Oltu','Olur','Palandöken','Pasinler','Pazaryolu','Şenkaya','Tekman','Tortum','Uzundere','Yakutiye'] },
  { name: 'Eskişehir', plateCode: 26, districts: ['Alpu','Beylikova','Çifteler','Günyüzü','Han','İnönü','Mahmudiye','Mihalgazi','Mihalıççık','Odunpazarı','Sarıcakaya','Seyitgazi','Sivrihisar','Tepebaşı'] },
  { name: 'Gaziantep', plateCode: 27, districts: ['Araban','İslahiye','Karkamış','Nizip','Nurdağı','Oğuzeli','Şahinbey','Şehitkamil','Yavuzeli'] },
  { name: 'Giresun', plateCode: 28, districts: ['Alucra','Bulancak','Çamoluk','Çanakçı','Dereli','Doğankent','Espiye','Eynesil','Giresun Merkez','Görele','Güce','Keşap','Piraziz','Şebinkarahisar','Tirebolu','Yağlıdere'] },
  { name: 'Gümüşhane', plateCode: 29, districts: ['Gümüşhane Merkez','Kelkit','Köse','Kürtün','Şiran','Torul'] },
  { name: 'Hakkari', plateCode: 30, districts: ['Çukurca','Derecik','Hakkari Merkez','Şemdinli','Yüksekova'] },
  { name: 'Hatay', plateCode: 31, districts: ['Altınözü','Antakya','Arsuz','Belen','Defne','Dörtyol','Erzin','Hassa','İskenderun','Kırıkhan','Kumlu','Payas','Reyhanlı','Samandağ','Serinyol','Yayladağı'] },
  { name: 'Isparta', plateCode: 32, districts: ['Aksu','Atabey','Eğirdir','Gelendost','Gönen','Keçiborlu','Senirkent','Sütçüler','Şarkikaraağaç','Uluborlu','Yalvaç','Yenişarbademli','Isparta Merkez'] },
  { name: 'Mersin', plateCode: 33, districts: ['Akdeniz','Anamur','Aydıncık','Bozyazı','Çamlıyayla','Erdemli','Gülnar','Mezitli','Mut','Silifke','Tarsus','Toroslar','Yenişehir'] },
  { name: 'İstanbul', plateCode: 34, districts: ['Adalar','Arnavutköy','Ataşehir','Avcılar','Bağcılar','Bahçelievler','Bakırköy','Başakşehir','Bayrampaşa','Beşiktaş','Beykoz','Beylikdüzü','Beyoğlu','Büyükçekmece','Çatalca','Çekmeköy','Esenler','Esenyurt','Eyüpsultan','Fatih','Gaziosmanpaşa','Güngören','Kadıköy','Kağıthane','Kartal','Küçükçekmece','Maltepe','Pendik','Sancaktepe','Sarıyer','Silivri','Sultanbeyli','Sultangazi','Şile','Şişli','Tuzla','Ümraniye','Üsküdar','Zeytinburnu'] },
  { name: 'İzmir', plateCode: 35, districts: ['Aliağa','Balçova','Bayındır','Bayraklı','Bergama','Beydağ','Bornova','Buca','Çeşme','Çiğli','Dikili','Foça','Gaziemir','Güzelbahçe','Karabağlar','Karaburun','Karşıyaka','Kemalpaşa','Kınık','Kiraz','Konak','Menderes','Menemen','Narlıdere','Ödemiş','Seferihisar','Selçuk','Tire','Torbalı','Urla'] },
  { name: 'Kars', plateCode: 36, districts: ['Akyaka','Arpaçay','Digor','Kağızman','Kars Merkez','Sarıkamış','Selim','Susuz'] },
  { name: 'Kastamonu', plateCode: 37, districts: ['Abana','Ağlı','Araç','Azdavay','Bozkurt','Çatalzeytin','Cide','Daday','Devrekani','Doğanyurt','Hanönü','İhsangazi','İnebolu','Kastamonu Merkez','Küre','Pınarbaşı','Seydiler','Şenpazar','Taşköprü','Tosya'] },
  { name: 'Kayseri', plateCode: 38, districts: ['Akkışla','Bünyan','Develi','Felahiye','Hacılar','İncesu','Kocasinan','Melikgazi','Özvatan','Pınarbaşı','Sarıoğlan','Sarız','Talas','Tomarza','Yahyalı','Yeşilhisar'] },
  { name: 'Kırklareli', plateCode: 39, districts: ['Babaeski','Demirköy','Kırklareli Merkez','Kofçaz','Lüleburgaz','Pehlivanköy','Pınarhisar','Vize'] },
  { name: 'Kırşehir', plateCode: 40, districts: ['Akçakent','Akpınar','Boztepe','Çiçekdağı','Kaman','Kırşehir Merkez','Mucur'] },
  { name: 'Kocaeli', plateCode: 41, districts: ['Başiskele','Çayırova','Darıca','Derince','Dilovası','Gebze','Gölcük','İzmit','Kandıra','Karamürsel','Kartepe','Körfez'] },
  { name: 'Konya', plateCode: 42, districts: ['Ahırlı','Akören','Akşehir','Altınekin','Beyşehir','Bozkır','Cihanbeyli','Çeltik','Çumra','Derbent','Derebucak','Doğanhisar','Emirgazi','Ereğli','Güneysınır','Hadim','Halkapınar','Hüyük','Ilgın','Kadınhanı','Karapınar','Karatay','Kulu','Meram','Sarayönü','Selçuklu','Seydişehir','Taşkent','Tuzlukçu','Yalıhüyük','Yunak'] },
  { name: 'Kütahya', plateCode: 43, districts: ['Altıntaş','Aslanapa','Çavdarhisar','Domaniç','Dumlupınar','Emet','Gediz','Hisarcık','Kütahya Merkez','Pazarlar','Simav','Şaphane','Tavşanlı'] },
  { name: 'Malatya', plateCode: 44, districts: ['Akçadağ','Arapgir','Arguvan','Battalgazi','Darende','Doğanşehir','Doğanyol','Hekimhan','Kale','Kuluncak','Pütürge','Yazıhan','Yeşilyurt'] },
  { name: 'Manisa', plateCode: 45, districts: ['Ahmetli','Akhisar','Alaşehir','Demirci','Gölmarmara','Gördes','Kırkağaç','Köprübaşı','Kula','Salihli','Sarıgöl','Saruhanlı','Selendi','Soma','Şehzadeler','Turgutlu','Yunusemre'] },
  { name: 'Kahramanmaraş', plateCode: 46, districts: ['Afşin','Andırın','Çağlayancerit','Dulkadiroğlu','Ekinözü','Elbistan','Göksun','Nurhak','Onikişubat','Pazarcık','Türkoğlu'] },
  { name: 'Mardin', plateCode: 47, districts: ['Artuklu','Dargeçit','Derik','Kızıltepe','Mazıdağı','Midyat','Nusaybin','Ömerli','Savur','Yeşilli'] },
  { name: 'Muğla', plateCode: 48, districts: ['Bodrum','Dalaman','Datça','Fethiye','Kavaklıdere','Köyceğiz','Marmaris','Menteşe','Milas','Ortaca','Seydikemer','Ula','Yatağan'] },
  { name: 'Muş', plateCode: 49, districts: ['Bulanık','Hasköy','Korkut','Malazgirt','Merkez','Varto'] },
  { name: 'Nevşehir', plateCode: 50, districts: ['Acıgöl','Avanos','Derinkuyu','Gülşehir','Hacıbektaş','Kozaklı','Nevşehir Merkez','Ürgüp'] },
  { name: 'Niğde', plateCode: 51, districts: ['Altunhisar','Bor','Çamardı','Çiftlik','Niğde Merkez','Ulukışla'] },
  { name: 'Ordu', plateCode: 52, districts: ['Akkuş','Altınordu','Aybastı','Çamaş','Çatalpınar','Çaybaşı','Fatsa','Gölköy','Gülyalı','Gürgentepe','İkizce','Kabadüz','Kabataş','Korgan','Kumru','Mesudiye','Perşembe','Ulubey','Ünye'] },
  { name: 'Rize', plateCode: 53, districts: ['Ardeşen','Çamlıhemşin','Çayeli','Derepazarı','Fındıklı','Güneysu','Hemşin','İkizdere','İyidere','Kalkandere','Pazar','Rize Merkez'] },
  { name: 'Sakarya', plateCode: 54, districts: ['Adapazarı','Akyazı','Arifiye','Erenler','Ferizli','Geyve','Hendek','Karapürçek','Karasu','Kaynarca','Kocaali','Mithatpaşa','Pamukova','Sapanca','Serdivan','Söğütlü','Taraklı'] },
  { name: 'Samsun', plateCode: 55, districts: ['Alaçam','Asarcık','Atakum','Ayvacık','Bafra','Canik','Çarşamba','Havza','İlkadım','Kavak','Ladik','Ondokuzmayıs','Salıpazarı','Tekkeköy','Terme','Vezirköprü','Yakakent'] },
  { name: 'Siirt', plateCode: 56, districts: ['Baykan','Eruh','Kurtalan','Pervari','Siirt Merkez','Şirvan','Tillo'] },
  { name: 'Sinop', plateCode: 57, districts: ['Ayancık','Boyabat','Dikmen','Durağan','Erfelek','Gerze','Saraydüzü','Sinop Merkez','Türkeli'] },
  { name: 'Sivas', plateCode: 58, districts: ['Akıncılar','Altınyayla','Divriği','Doğanşar','Gemerek','Gölova','Gürün','Hafik','İmranlı','Kangal','Koyulhisar','Sivas Merkez','Suşehri','Şarkışla','Ulaş','Yıldızeli','Zara'] },
  { name: 'Tekirdağ', plateCode: 59, districts: ['Çerkezköy','Çorlu','Ergene','Hayrabolu','Kapaklı','Malkara','Marmaraereğlisi','Muratlı','Saray','Süleymanpaşa','Şarköy'] },
  { name: 'Tokat', plateCode: 60, districts: ['Almus','Artova','Başçiftlik','Erbaa','Niksar','Pazar','Reşadiye','Sulusaray','Tokat Merkez','Turhal','Yeşilyurt','Zile'] },
  { name: 'Trabzon', plateCode: 61, districts: ['Akçaabat','Araklı','Arsin','Beşikdüzü','Çarşıbaşı','Çaykara','Dernekpazarı','Düzköy','Hayrat','Köprübaşı','Maçka','Of','Ortahisar','Şalpazarı','Sürmene','Tonya','Vakfıkebir','Yomra'] },
  { name: 'Tunceli', plateCode: 62, districts: ['Çemişgezek','Hozat','Mazgirt','Nazımiye','Ovacık','Pertek','Pülümür','Tunceli Merkez'] },
  { name: 'Şanlıurfa', plateCode: 63, districts: ['Akçakale','Birecik','Bozova','Ceylanpınar','Eyyübiye','Halfeti','Haliliye','Harran','Hilvan','Karaköprü','Siverek','Suruç','Viranşehir'] },
  { name: 'Uşak', plateCode: 64, districts: ['Banaz','Eşme','Karahallı','Sivaslı','Ulubey','Uşak Merkez'] },
  { name: 'Van', plateCode: 65, districts: ['Bahçesaray','Başkale','Çaldıran','Çatak','Edremit','Erciş','Gevaş','Gürpınar','İpekyolu','Muradiye','Özalp','Saray','Tuşba'] },
  { name: 'Yozgat', plateCode: 66, districts: ['Akdağmadeni','Aydıncık','Boğazlıyan','Çandır','Çayıralan','Çekerek','Kadışehri','Saraykent','Sarıkaya','Şefaatli','Sorgun','Yenifakılı','Yerköy','Yozgat Merkez'] },
  { name: 'Zonguldak', plateCode: 67, districts: ['Alaplı','Çaycuma','Devrek','Ereğli','Gökçebey','Kilimli','Kozlu','Zonguldak Merkez'] },
  { name: 'Aksaray', plateCode: 68, districts: ['Ağaçören','Aksaray Merkez','Eskil','Gülağaç','Güzelyurt','Ortaköy','Sarıyahşi','Sultanhanı'] },
  { name: 'Bayburt', plateCode: 69, districts: ['Aydıntepe','Bayburt Merkez','Demirözü'] },
  { name: 'Karaman', plateCode: 70, districts: ['Ayrancı','Başyayla','Ermenek','Karaman Merkez','Kazımkarabekir','Sarıveliler'] },
  { name: 'Kırıkkale', plateCode: 71, districts: ['Bahşili','Balışeyh','Çelebi','Delice','Karakeçili','Keskin','Kırıkkale Merkez','Sulakyurt','Yahşihan'] },
  { name: 'Batman', plateCode: 72, districts: ['Batman Merkez','Beşiri','Gercüş','Hasankeyf','Kozluk','Sason'] },
  { name: 'Şırnak', plateCode: 73, districts: ['Beytüşşebap','Cizre','Güçlükonak','İdil','Silopi','Şırnak Merkez','Uludere'] },
  { name: 'Bartın', plateCode: 74, districts: ['Amasra','Bartın Merkez','Kurucaşile','Ulus'] },
  { name: 'Ardahan', plateCode: 75, districts: ['Ardahan Merkez','Çıldır','Damal','Göle','Hanak','Posof'] },
  { name: 'Iğdır', plateCode: 76, districts: ['Aralık','Iğdır Merkez','Karakoyunlu','Tuzluca'] },
  { name: 'Yalova', plateCode: 77, districts: ['Altınova','Armutlu','Çınarcık','Çiftlikköy','Termal','Yalova Merkez'] },
  { name: 'Karabük', plateCode: 78, districts: ['Eflani','Eskipazar','Karabük Merkez','Ovacık','Safranbolu','Yenice'] },
  { name: 'Kilis', plateCode: 79, districts: ['Elbeyli','Kilis Merkez','Musabeyli','Polateli'] },
  { name: 'Osmaniye', plateCode: 80, districts: ['Bahçe','Düziçi','Hasanbeyli','Kadirli','Osmaniye Merkez','Sumbas','Toprakkale'] },
  { name: 'Düzce', plateCode: 81, districts: ['Akçakoca','Cumayeri','Çilimli','Düzce Merkez','Gölyaka','Gümüşova','Kaynaşlı','Yığılca'] },
];
